project_id = "wrvvlmevpvcenauglcyz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[functions.alerts-websocket]
verify_jwt = false

[functions.beehiiv-automated-sync]
verify_jwt = false

[functions.beehiiv-webhook]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.whop-gatekeeper]
verify_jwt = false

[functions.enhanced-auth]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.database-backup]
verify_jwt = false

[functions.beehiiv-auth]
verify_jwt = false

[functions.beehiiv-subscriber-verify]
verify_jwt = false

[functions.unified-auth-verify]
verify_jwt = false

[functions.whop-oauth-init]
verify_jwt = false

[functions.whop-oauth-exchange]
verify_jwt = false

[functions.list-all-users]
verify_jwt = false

[functions.admin-user-actions]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.beehiiv-debug]
verify_jwt = false

[functions.newsletter-date-fix]
verify_jwt = false

[functions.fix-newsletter-dates]
verify_jwt = false

[functions.bridge-auth-session]
verify_jwt = false

[functions.create-local-user]
verify_jwt = false

[functions.verify-2fa-token]
verify_jwt = false

[functions.create-2fa-session]
verify_jwt = false

[functions.verify-2fa-session]
verify_jwt = false

[functions.beehiiv-user-sync]
verify_jwt = false

[functions.video-proxy]
verify_jwt = false