project_id = "wrvvlmevpvcenauglcyz"

[auth]
# Enable auth webhook for custom email handling
enable_signup = true
enable_confirmations = false
external_email_enabled = true
hook_send_email_enabled = true
hook_send_email_uri = "https://wrvvlmevpvcenauglcyz.supabase.co/functions/v1/auth-webhook"

[functions.auth-webhook]
verify_jwt = false

[functions.active-alerts-widget]
verify_jwt = false

[functions.beehiiv-subscriber-verify]
verify_jwt = false

[functions.beehiiv-create-subscription]
verify_jwt = false

[functions.unified-auth-verify]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.verify-magic-link]
verify_jwt = false

[functions.crypto-pricing]
verify_jwt = false

[functions.degen-call-notifier]
verify_jwt = false