project_id = "wrvvlmevpvcenauglcyz"

[auth]
# Route all auth emails through our custom Resend function
hook_auth_emails_url = "https://wrvvlmevpvcenauglcyz.supabase.co/functions/v1/auth-emails"
hook_auth_emails_enabled = true

[functions.auth-emails]
verify_jwt = false

[functions.beehiiv-subscriber-verify]
verify_jwt = false

[functions.beehiiv-create-subscription]
verify_jwt = false

[functions.unified-auth-verify]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.crypto-pricing]
verify_jwt = false

[functions.degen-call-notifier]
verify_jwt = false