project_id = "wrvvlmevpvcenauglcyz"

[auth]
# Disable Supabase email sending - we handle emails via custom functions
enable_signup = true
enable_confirmations = false
external_email_enabled = false
hook_send_email_enabled = false

[functions.active-alerts-widget]
verify_jwt = false

[functions.beehiiv-subscriber-verify]
verify_jwt = false

[functions.beehiiv-create-subscription]
verify_jwt = false

[functions.unified-auth-verify]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.verify-magic-link]
verify_jwt = false

[functions.crypto-pricing]
verify_jwt = false

[functions.degen-call-notifier]
verify_jwt = false

[functions.price-aggregate]
verify_jwt = false

[functions.signal-engine]
verify_jwt = false