project_id = "wrvvlmevpvcenauglcyz"

[auth]
# Custom auth handled by send-magic-link function
hook_auth_emails_enabled = false

[functions.active-alerts-widget]
verify_jwt = false

[functions.beehiiv-subscriber-verify]
verify_jwt = false

[functions.beehiiv-create-subscription]
verify_jwt = false

[functions.unified-auth-verify]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.crypto-pricing]
verify_jwt = false

[functions.degen-call-notifier]
verify_jwt = false